_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 128
dataset:
    value: CIFAR-100
learning_rate:
    value: 0.01
